### ISSUE TITLE
[Flink19] Test from file doesn't work with kafka sources

### ISSUE THREAD

**Issue by arkadius** [TouK/nussknacker-flink-compatibility#9]
`KafkaDeserializationSchema.deserialize` has changed signature across versions: 

```
org.apache.flink.streaming.connectors.kafka.KafkaDeserializationSchema.deserialize(Lorg/apache/kafka/clients/consumer/ConsumerRecord;Lorg/apache/flink/util/Collector;)V, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[nussknacker-ui]
java.lang.NoSuchMethodError: org.apache.flink.streaming.connectors.kafka.KafkaDeserializationSchema.deserialize(Lorg/apache/kafka/clients/consumer/ConsumerRecord;Lorg/apache/flink/util/Collector;)V
	at pl.touk.nussknacker.engine.kafka.source.KafkaSource.deserializeTestData(KafkaSource.scala:72)
	at pl.touk.nussknacker.engine.kafka.source.KafkaSource$$anon$1$$anonfun$parseTestData$1.apply(KafkaSource.scala:61)
	at pl.touk.nussknacker.engine.kafka.source.KafkaSource$$anon$1$$anonfun$parseTestData$1.apply(KafkaSource.scala:61)
	at scala.collection.immutable.List.map(List.scala:284)
	at pl.touk.nussknacker.engine.kafka.source.KafkaSource$$anon$1.parseTestData(KafkaSource.scala:61)
	at pl.touk.nussknacker.engine.process.compiler.TestFlinkProcessCompiler$$anonfun$prepareSourceFactory$1.apply(TestFlinkProcessCompiler.scala:36)

```

**Comment by arkadius** [comment]
Fixed by: https://github.com/TouK/nussknacker/pull/1732
